### ISSUE TITLE
[Feature Request] 任意のTenKeyスタイルのカスタムタブファイルをアプリケーション内で編集可能にする

### ISSUE THREAD

**Issue by nakkisan** [ensan-hcl/azooKey#156]
**Describe the bug (不具合を説明してください)**

jsonファイルを読み込んで作成したカスタムタブが編集できない

**To Reproduce (どのような手順で実行すると不具合が生じるのか、詳しく教えてください)**

1. 自分が作成したカスタムタブの編集画面で、「共有」をタップして、iCloud上にjsonファイルを保存する
2. カスタムタブを削除してから、iCloud上でjsonファイルを読み込む
3. カスタムタブは正常に読み込めるが、読み込んだカスタムタブの設定画面には「編集する」というボタンが表示されず、編集不可となってしまう

**Expected behavior (どういう動作になるのが正しいと思いますか？)**

編集ができること

**Screenshots (スクリーンショットがあれば添付してください)**

![image](https://user-images.githubusercontent.com/21346086/232006333-cc09cd08-7854-4439-82f7-0a9eb8f34eba.png)

**Environment (環境を詳しく教えてください):**
 - Device: iPhone 13 Pro
 - iOS / iPadOS and its version: iOS 16.5 (20F5028e)
 - App Running Keyboard azookey
 - App Version 2.1.0

**Is it possible to keep in touch with you on an ongoing basis to fix this bug? (バグの修正のため、継続的なやり取りは可能ですか？)**

はい

**Additional context (その他共有したい事項があれば記述してください)**

**Comment by ensan-hcl** [comment]
ご報告ありがとうございます！

書き出したファイルには編集に必要なデータが含まれていないため、現在は「書き出し→読み込み」をやると編集が不可能になります。（他者の作ったカスタムタブを編集できないのも同様の理由です）

ただ、実際問題不便なので、どうにか解決できないか考えてみます！

**Comment by nakkisan** [comment]
ご丁寧な対応ありがとうございます。
おかげさまで現状が把握できました🙂

いくつかの設定を設定プロファイル感覚で切り替えてみよう、と思って切り替えてみたら……という事故は起こっちゃいそうですよね笑

お手数をおかけしますが、ご検討をお願いします😌

**Comment by ensan-hcl** [comment]
Tasks
- [ ] `replace_default `と `replace_last_characters`をazooKey App内で編集可能にする
- [ ] `smart_delete`と`smart_move_cursor`をazooKey App内で編集可能にする
- [ ] `pc` styleのカスタムタブをazooKey App内で編集可能にする
