### ISSUE TITLE
[Docs] Xcodeでのビルド方法を明確化する

### ISSUE THREAD

**Issue by N-i-ke** [ensan-hcl/azooKey#175]
[README.md]の手順通り、azooKey-featureブランチをcloneし、Keyboard/Converter/配下にDictionaryファイルを配置した後にビルドした際に発生したエラー"Signing for "azooKey" requires a development team"について

自分で対処してみたこと
・teamをnoneにして再実行
・Personalのアカウントにして再実行

実行環境
Xcode環境　Version 14.3 

初歩的なエラーですが回答いただけたら嬉しいです。

**Comment by ensan-hcl** [comment]
Google Driveから`Dictionary`全体をダウンロードして配置しましたか？

**Comment by N-i-ke** [comment]
Dictionary全体ではなく2.0/Dictionary/louds/charID.chidファイル単体のみを配置してビルドしてしまいました。

ご指摘いただいたとおり2.1.1のDictionaryをダウンロードし、上書きし配置し実行しましたところ問題なくビルドできました。

ご回答ありがとうございます！

**Comment by ensan-hcl** [comment]
なるほど！これはREADMEの書き方が良くなかったですね。後で変更しておきます！
