### ISSUE TITLE
[Refactoring] `toVersionCandidate`を別のファイルに切り出す

### ISSUE THREAD

**Issue by ensan-hcl** [ensan-hcl/azooKey#180]
現在、`toVersionCandidate`という関数が`Wareki.swift`に含まれている。ファイルの名称にそぐわず適切ではないので、以下を行いたい。
- [ ] `VersionCandidate.swift`というファイルを新たに追加してそこに切り出したい
- [ ] `Wareki.swift`の名前も`CalendarCandidate.swift`に変更したい
https://github.com/ensan-hcl/azooKey/blob/0b0a11486472cb25d0ecacaecc066cb843648868/Keyboard/Converter/Converter/Wareki.swift#L12-L28

**Comment by N-i-ke** [comment]
取り組んでいいですか！？

**Comment by ensan-hcl** [comment]
お願いします！

**Comment by ensan-hcl** [comment]
Fixed in #187
