### ISSUE TITLE
[Feature Request] AzooKeyCore(KanaKanjiConverterModule)を別途OSSとして切り出す

### ISSUE THREAD

**Issue by Kyome22** [ensan-hcl/azooKey#221]
**Is your feature request related to a problem? Please describe. (提案は利用上の問題に関連していますか？記述してください。)**
AzooKeyのかな漢字変換エンジン（KanaKanjiConverterModule）を別アプリで利用したいが、AzooKeyアプリのローカルパッケージなので（リポジトリにルートにPackage.swiftが配置されていないので）SPMでfetchすることができない。

**Describe the solution you'd like (あなたの考える解決策を記述してください)**
AzooKeyCoreの内かな漢字変換に必要なモジュールを別リポジトリに分けてimportするように変更するといいと思います。
ただ、その場合も変換にGoogleDriveの辞書が必要なので、ただimportするだけでは動かないPackageになってしまうと思います。
そのため、GoogleDriveから辞書データをインストールしてくる処理をSwift PackageのPluginにしてPre Build時に実行されるようにするといいかもしれません。（多分できるはず？）

**Describe alternatives you've considered (他の解決方法があれば記述してください)**
Package.swiftの置き場所と書くtargetのPathを工夫すれば今のリポジトリ構成でもいけるかも？

**If we were to implement this feature, will you help implement it? (もし提案する機能を実装する場合、実装を手伝う余裕はありますか？)**
Swift Package Pluginに関する質問なら受け付けます！

**Additional context (その他共有したい事項があれば記述してください)**
Swift製のかな漢字変換エンジンの実装/ 公開は素晴らしい功績だと思います！

**Comment by ensan-hcl** [comment]
ありがとうございます！この問題は対処したいと思っていて、方法を考えていたところでした。直近別のリファクタリングが進んでいるのですぐには対処できないのですが、数週間以内に移行できると思います。

> Package.swiftの置き場所と書くtargetのPathを工夫すれば今のリポジトリ構成でもいけるかも？

これは #217 で少し試していて、動作には問題がないのですが、Xcode側の処理に不安があったので一旦止めました。
> AzooKeyCoreの内かな漢字変換に必要なモジュールを別リポジトリに分けてimportするように変更するといいと思います。

なので、こちらの線で進めていくことになると思います。

> ただ、その場合も変換にGoogleDriveの辞書が必要なので、ただimportするだけでは動かないPackageになってしまうと思います。
> そのため、GoogleDriveから辞書データをインストールしてくる処理をSwift PackageのPluginにしてPre Build時に実行されるようにするといいかもしれません。（多分できるはず？）

辞書データは厳密にはパッケージと切り離していて、KanaKanjiConverterModuleを動かすときはオプションの中でazooKeyにバンドルした辞書データのURLを指定する仕組みになっています。KanaKanjiConverterModuleのリソースとして扱うわけではないので、どこにインストールするかが問題になります。

現在、インストールした辞書データはパッケージ外部のazooKey/Keyboard/Dictionaryに配置するようになっていますが、KanaKanjiConverterModuleを切り出す場合はどこに配置すると嬉しいかよくわかりません。
単にパッケージ内に配置しても良いとは思うのですが、一旦は自動インストールはなしで単純にパッケージそのものを切り出すことになると思います。

**Comment by ensan-hcl** [comment]
> 直近別のリファクタリングが進んでいるのですぐには対処できないのですが、数週間以内に移行できると思います。

と思っていたんですが、別にプロジェクト自体の切り出しはすぐできるのでやりました！

https://github.com/ensan-hcl/AzooKeyKanaKanjiConverter

**Comment by ensan-hcl** [comment]
辞書ですが、Swift Pluginを利用した辞書データのダウンロードが問題なくできそうであれば、[AzooKeyKanaKanjiConverter](https://github.com/ensan-hcl/AzooKeyKanaKanjiConverter)の中に`DefaultDitionary`というモジュールを追加し、これのリソースにしようと思います。利用側は`DefaultDictionary`のリソースをConverterRequestOptionsに指定することで手間なく変換ができます。

**Comment by Kyome22** [comment]
> 辞書ですが、Swift Pluginを利用した辞書データのダウンロードが問題なくできそうであれば、[AzooKeyKanaKanjiConverter](https://github.com/ensan-hcl/AzooKeyKanaKanjiConverter)の中に`DefaultDitionary`というモジュールを追加し、これのリソースにしようと思います。利用側は`DefaultDictionary`のリソースをConverterRequestOptionsに指定することで手間なく変換ができます。

例として[LicenseList](https://github.com/cybozu/LicenseList/blob/main/Plugins/PrepareLicenseList/main.swift)ではSwift Plugin (buildCommand)で生成した`license-list.plist`というファイルをMainのBundleリソースに配置して、デフォルトでは実行時にそれを読み込むようにしています。なので、辞書データをフェッチしてくるCommandLineToolをSwiftで書いてPlugin実行すれば自動でビルドできるようになるんじゃないかと思います。

**Comment by Kyome22** [comment]
↑この場合、`DefaultDictionary`というモジュールは不要で、`PrepareDictionaryPlugin`みたいなものを用意するだけで良いと思います。

**Comment by ensan-hcl** [comment]
なるほど、知らなかったのでLicenseListを試してみました。こういう挙動が出来るんですね。

ただ、BuildToolPluginはどうやらネットワークアクセスが出来ないようです😇（[参考](https://qiita.com/maiyama18/items/3d0f7b288c6858b751ce#%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF%E9%80%9A%E4%BF%A1)）

なので、今できる範囲だと辞書データは手動で降ろしてくるか、意地でGitにデータを突っ込むか、という感じになりますね・・・。

**Comment by Kyome22** [comment]
BuildToolPluginではネットワークアクセスができないというのは知りませんでした。残念ですね...

**Comment by ensan-hcl** [comment]
切り出し自体は実施したのでこのIssueは一旦closeします。辞書については以下で引き続き検討します。
https://github.com/ensan-hcl/AzooKeyKanaKanjiConverter/issues/3
