### ISSUE TITLE
[Feature Request] カーソルをカーソルUI以外で移動した際に、バーをカーソルUIに変更する

### ISSUE THREAD

**Issue by nyanko3141592** [ensan-hcl/azooKey#276]
**Is your feature request related to a problem? Please describe. (提案は利用上の問題に関連していますか？記述してください。)**
テキストフィールドの中でカーソルを移動した際にカーソルのボタンをタップしてバーを切り替えてカーソルUIで細かく移動などをおこないたい

**Describe the solution you'd like (あなたの考える解決策を記述してください)**
カーソル移動を検知して自動でカーソルUIが表示するようにする
変換途中でのカーソル移動
- ライブ変換の場合はカーソル移動をした際にカーソルUIを表示
- ライブ変換でない場合はカーソル移動してもカーソルUIを表示しない

**Describe alternatives you've considered (他の解決方法があれば記述してください)**

**If we were to implement this feature, will you help implement it? (もし提案する機能を実装する場合、実装を手伝う余裕はありますか？)**
実装してプルリク出します

**Additional context (その他共有したい事項があれば記述してください)**

**Comment by ensan-hcl** [comment]
> テキストフィールドの中でカーソルを移動した際にカーソルのボタンをタップしてバーを切り替えてカーソルUIで細かく移動などをおこないたい

* 「テキストフィールドの中でカーソルを移動した際に、カーソルのボタンをタップして表示するカーソルUI（カーソルバー）を表示したい」との意味ですか？

> * ライブ変換の場合はカーソル移動をした際にカーソルUIを表示
> * ライブ変換でない場合はカーソル移動してもカーソルUIを表示しない

良いと思います。

> 実装してプルリク出します

ありがとうございます、確認します！
