### ISSUE TITLE
[Feature Request]フリックした時のSuggestViewの表示を改善する

### ISSUE THREAD

**Issue by nyanko3141592** [ensan-hcl/azooKey#278]
**Is your feature request related to a problem? Please describe. (提案は利用上の問題に関連していますか？記述してください。)**
現在のフリックキーボードの入力がわかりにくい。
一般的なキーボードのようにバルーンの表示機能をON/OFFできるようにしたい

![image](https://github.com/ensan-hcl/azooKey/assets/43579605/9187b159-7d75-48a4-84be-9fc94a9f6184)

**Describe the solution you'd like (あなたの考える解決策を記述してください)**
フリックによるバルーンの追加
コンテントアプリ側でのこれのON/OFFを選択できるようにする

**Describe alternatives you've considered (他の解決方法があれば記述してください)**

**If we were to implement this feature, would you help implement it? (もし提案する機能を実装する場合、実装を手伝う余裕はありますか？)**
実装してプルリクを投げます

**Additional context (その他共有したい事項があれば記述してください)**

**Comment by ensan-hcl** [comment]
> コンテントアプリ側でのこれのON/OFFを選択できるようにする

ここを実際にやるかどうかはちょっと考えたいので、SettingProviderProtocol(?)みたいなやつに一旦bool値を追加しておいてもらえますか？

**Comment by nyanko3141592** [comment]
了解です
BetaのCursorUIのような形の取り込み型の方が良いと思います

**Comment by ensan-hcl** [comment]
良さそうです。実装お願いします！
