### ISSUE TITLE
[Feature Request] shiftキーの位置を「Z」の左側に移動してほしい

### ISSUE THREAD

**Issue by justyuya** [ensan-hcl/azooKey#379]
純正キーボードや他社製キーボードと同じようにshiftキーの位置の位置をAの隣ではなくZの隣になるようにしてほしい。

**Comment by ensan-hcl** [comment]
ご要望ありがとうございます。検討のため、いくつか追加で教えてくださいませ。
* その位置には現在日本語と英語を切り替えるキーが表示されていますが、Zの隣にshiftキーを移動する場合、このキーはどこに置くのが妥当だと思われますか？
* どれくらい困っていますか？（慣れれば問題ない/慣れたが不満/全く慣れない）

**Comment by justyuya** [comment]
日本語と英語を切り替えるキーを現在の数字キーのところへ持ってきて、数字キーと記号キーを統合してしまうのがいいと思います。
Aのある列が全体的に一つ分右に寄るので慣れません。タイプミスしてしまいます。

**Comment by ensan-hcl** [comment]
なるほど、ありがとうございます。確かに列全体が移動してしまうのは仕様として不適切だと感じます。

一方で、修正の方法については難しい点がいくつかあり、進め方は迷うところです。

* すでにリリース済みの機能である（デフォルトを変更すると影響を受けるユーザが多い）
  * シフトキーの位置自体は変更できる
  * 数字キー・記号キーの位置の変更が変わるのはかなり混乱を招く
 
オプションとして修正を入れる、シフトキーをLの右に配置するなど、いくつか解決策が考えられるので、少し検討させていたdかいます。

**Comment by justyuya** [comment]
オプションとして修正を入れるのがベストかと思います。

**Comment by ensan-hcl** [comment]
### 現状の理想的な仕様変更

関連するオプション
* ホームボタンのある端末か否か（地球儀キーの有無）
* 言語設定がどうなっているか（第二言語の有無）


```
[X] [z][x][c][v][b][n][m] [<]
[Y] [Z]  [  space  ]  [enter]
```
ここにシフトキーによるキー配置変更を考える場合、次のようになる。各場合ごとに上記のX, Y, Zを記述する。

1. ホームボタンあり・第二言語あり
   このケースでは
    * 英語タブ→`(X: ↑, Y: Aあ, Z: #+=)`
    * 日本語タブ→`(X: 123, Y: あA, Z: #+=)`
1. ホームボタンなし・第二言語あり
   このケースでは
    * 英語タブ→`(X: ↑, Y: Aあ, Z: 🌐)`
    * 日本語タブ→`(X: 123, Y: あA, Z: 🌐)`
1. ホームボタンあり・第二言語なし（第一言語が英語）
   このケースでは
    * 英語タブ→`(X: ↑, Y: 123, Z: #+=)`
1. ホームボタンなし・第二言語なし（第一言語が英語）
   このケースでは
    * 英語タブ→`(X: ↑, Y: #+=, Z:  🌐)`

---

既存のシフトキーユーザには引き続き現在の挙動を提供しつつ、新規に設定する際は新しい挙動のみ選べる形にする。

iOS 18以降で既存のシフトキーユーザにも新しい挙動を強制することで、オプション化を防ぐ。

### 評価

理想的ではあるが、現状以上に仕様が複雑になる仕様変更なので、もう少し安くどうにかする方法を検討したい。

**Comment by ensan-hcl** [comment]
Alternative design。（空き位置に配置した&はプレイスホルダー）
* こちらであれば全体の遷移ボタンの配置替えが不要なため、既存ユーザにとっても分かりやすい
* 標準キーボードとは違ってシフトキーはZキーの隣ではなくなってしまうが「慣れれば大丈夫」なタイプのボタンであると期待

<img width="375" alt="image" src="https://github.com/ensan-hcl/azooKey/assets/63481257/e0071c61-c2ef-4ba7-bdf7-86542774785f">

**Comment by ensan-hcl** [comment]
Version 2.2.3でオプション自体は導入します。「&」キーの位置にはピリオドを置くつもりです。

**Comment by ensan-hcl** [comment]
@justyuya こちら一旦実装し、TestFlight経由でベータ版の配信を始めました。もしよろしければこちらのリンクからベータ版をお試しいただければと思います。
アプリ内の設定で「シフトキーを使う」の下部にある「古いシフトキーの挙動を使う」をオフにしていただければ、修正版の挙動になります。

https://testflight.apple.com/join/x6TKEeB2

**Comment by justyuya** [comment]
対応ありがとうございます。
