### ISSUE TITLE
[Feature Request] Qwertyキーボードでキー長押しで数字や記号を入力できるようにしてほしい

### ISSUE THREAD

**Issue by justyuya** [ensan-hcl/azooKey#380]
QWERTY配列でキー長押しで数字や記号を入力できるようにしてほしい。

**Comment by ensan-hcl** [comment]
ご要望ありがとうございます。類似の要望はいくつか上がっているのですが、今のところはあまり高い優先度をつけていません。
どちらかというと、カスタムタブ機能でカスタムQwertyキーボードを作成可能にする方向で進めたいと考えています。
