### ISSUE TITLE
[Feature Request] カーソル移動機能を標準キーボード風にしたい

### ISSUE THREAD

**Issue by justyuya** [ensan-hcl/azooKey#381]
スペースキー長押しでカーソル移動ができる機能の挙動を、純正キーボードのようなキーの文字が消え、キーボード全体をスワイプできて、一文字ごとに触覚フィードバックがあるようなものにしてほしい。
スペースキーから一回指を離さないといけないのが少し不便に思う。

**Comment by ensan-hcl** [comment]
ご要望ありがとうございます。カーソル移動機能については今後のバージョンで改善する意欲があります

一方、カーソル移動機能については可能な仕様の幅がかなり広く、仰るような標準キーボード風の仕様も含めてさまざま検討したいと考えています！

**Comment by justyuya** [comment]
オプション化するのがいいかもしれません。

**Comment by ensan-hcl** [comment]
オプション化は一つの手段ですが、機能を維持する開発コストが大きくなります。azooKeyは主に個人で開発しているプロジェクトですので、個人で管理可能な範囲を超えてしまわないよう注意深く進めたいと考えています。

**Comment by ensan-hcl** [comment]
一旦クローズします（カーソルバーについては別途対応します）
