### ISSUE TITLE
[BUG] iPad mini6でフローティングキーボードの動作が重い

### ISSUE THREAD

**Issue by ensan-hcl** [ensan-hcl/azooKey#382]
以下の不具合の報告をいただいたが、再現できていない。
再現を試みた環境

* M1 iPad Pro 11inch
* iPad mini (2016?)

---
**Describe the bug (不具合を説明してください)**
iPad mini6でフローティングキーボードの動作が重い

**To Reproduce (どのような手順で実行すると不具合が生じるのか、詳しく教えてください)**
1. azooKeyをフローティングキーボードにする
2. 入力する
3. フローティングキーボードでない場合より重たくなる

**Expected behavior (どういう動作になるのが正しいと思いますか？)**
通常モードと同等の軽量な動作

**Screenshots (スクリーンショットがあれば添付してください)**
N/A

**Environment (環境を詳しく教えてください):**
 - Device: iPad mini 第6世代
 - iOS / iPadOS and its version: iPadOS 17.1.2
 - App Running Keyboard: ChatGPT
 - App Version: azooKey 2.2.2

**Comment by k-taro56** [comment]
iPad mini 6 持っておりますが、特別重くなるとは感じませんね。

注意深く意識してみれば、かくつくことがあるような気がしますが、それがフローティングボード特有のものかはわかりません。

OS のバージョン含めてもう少し調べてみようは思います。

Environment (環境を詳しく教えてください):

- Device: iPad mini 第6世代
- iOS / iPadOS and its version: iPadOS 17
- App Running Keyboard: ChatGPT
- App Version: azooKey 2.2.2

**Comment by ensan-hcl** [comment]
ありがとうございます！！情報助かります。やはり再現しないんですね……
