### ISSUE TITLE
[Feature Request] フリックキーボードでの連打

### ISSUE THREAD

**Issue by taisan11** [ensan-hcl/azooKey#468]
IOSの標準キーボードでは連打すると文字を入力できるのでそれを実装して欲しいです。
例:あと書かれてるキーを3回連打する→確定を押すと「う」が入力される
iOSの開発はわかりません。

**Comment by ensan-hcl** [comment]
ご要望ありがとうございます。連打で文字が切り替わる、いわゆる携帯打ち（トグル入力）を実装するのは、開発負荷の問題で現在ペンディングにしています。誰か実装をやりきれるような方が手伝ってくださるのであれば導入したい、という状況です。こちらのイシューをご覧ください。

https://github.com/ensan-hcl/azooKey/issues/389
